version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: takip_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: takip_db
    ports:
      - '5432:5432'
    volumes:
      - takip_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  takip_postgres_data:
